### ISSUE TITLE
Add informative error messages to asserts

### ISSUE THREAD

**Issue by PaulKlint** [usethesource/vallang#158]
The valling code contains quite some asserts (very good!)
Unfortunately these asserts just throw `assertionError` without further information.
I just spent hours figuring out what went wrong.

Proposal add to all asserts informative error strings that describe (where relevant):
- arity
- expected type, found type,
- index of offending argument or field
-  ...

**Comment by jurgenvinju** [comment]
Which assert was causing you the most trouble @PaulKlint ? It is quite some work to go through all asserts now, but to do the most important is easy. I did the one which checks parameter types of constructor function calls in c7a511e

**Comment by PaulKlint** [comment]
So you picked the right one :-)

**Comment by jurgenvinju** [comment]
Yes, that's one that fails often when we write Java code to construct trees, like the Clair adapter or Java JDT AST producer. And a very costly one! If you run without asserts, the code is significantly faster for those two use cases.

**Comment by jurgenvinju** [comment]
I'm building a release so you can run with the new version.

**Comment by PaulKlint** [comment]
Great, thanks!

**Comment by jurgenvinju** [comment]
vallang-0.14.5 will be ready in a few minutes.
