### ISSUE TITLE
Entry Buckets in ShareableValuesHashSet typically nest 4 or 5 times during a transitive closure on source locations (call graph)

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/vallang#235]
I'm debugging a performance issue in transitive closures of large call graphs. 

* The profile shows how all of the memory and time goes to the temporary `ShareableValuesHashSet` that is used by the closure method of `PersistentHashIndexedBinaryRelation`
* Then all the memory runs out and GC takes over
* The heap dump shows at least 40% of the memory goes to Entry[] and Entry as held by `ShareableValuesHashSet`
* At every array index in de `ShareableValuesHashSet` we find an Entry that has a `next` field to a different entry with the same hash position, which has a next field, etc. All indices I've clicked on have at least 4 nesting levels deep, some go up to 5, 6, 7, 8.

Is this low-hanging fruit @msteindorfer ? If you have some thoughts to share, I'd be listening ;-) Otherwise, I'll start experimenting a bit in the coming days and weeks.

**Comment by jurgenvinju** [comment]
CC @linuswagner

**Comment by jurgenvinju** [comment]
```
public boolean add(IValue value){
		ensureCapacity();
		
		int hash = value.hashCode();
		int position = hash & hashMask;
		
		Entry<IValue> currentStartEntry = data[position];
		// Check if the value is already in here.
		if(currentStartEntry != null){
			Entry<IValue> entry = currentStartEntry;
			do{
				if(hash == entry.hash && entry.value.equals(value)){
					return false; // Return false if it's already present.
				}
				
				entry = entry.next;
			}while(entry != null);
		}
		
		data[position] = new Entry<>(hash, value, currentStartEntry); // Insert the new entry.
		
		load++;
		
		currentHashCode ^= hash; // Update the current hashcode of this map.
		
		return true;
	}
```

looks like the hashing is entirely decided on the hashcode of the values which are `persistent.Tuple` here, and xand'ed with the size of the hash table (power of 2).

**Comment by DavyLandman** [comment]
I've at some time written a transitive closure implementation that would use transient sets for some operations, and only freeze it at the end. Could that help out reduce all the intermediate sets?

Also, I like your idea of special casing the binary tuples, but aren't binary relations already encoded specially?

**Comment by DavyLandman** [comment]
> looks like the hashing is entirely decided on the hashcode of the values which are `persistent.Tuple` here, and xand'ed with the size of the hash table (power of 2).

isn't this just separate chaining? nothing wrong directly, as long as the hash codes are fine, and the table grows before it's completely full?

**Comment by jurgenvinju** [comment]
Another note: is weird we have all these intermediate persistent tuples that are immediately disregarded by the mulltimap that stores the result of the closure. Shouldn't we have an efficient union in amortized O(log n ) for disjoint unions or something? So we can use that to incrementally build the result. That would also save the entire duplicate in memory that we have now.

**Comment by DavyLandman** [comment]
why not pass in the `SetWriter` to the `computeClosureDelta`  function?

**Comment by jurgenvinju** [comment]
> > looks like the hashing is entirely decided on the hashcode of the values which are `persistent.Tuple` here, and xand'ed with the size of the hash table (power of 2).
> 
> isn't this just separate chaining? nothing wrong directly (might hurt locality etc), as long as the hash codes are fine, and the table grows before it's completely full?

It is chaining. It means lookups are on average 4 times as slow as they could be; at least in my mind.

**Comment by DavyLandman** [comment]
I think we can close this issue (and maybe remove the ShareableValuesHashSet again?)
