### ISSUE TITLE
Drop xz-java dependency

### ISSUE THREAD

**Issue by DavyLandman** [usethesource/vallang#252]
Considering recent news, we're trying to take a close peek at our dependencies, and the support behind them.

Now we actually depend on xz-java, which based on most analysis [doesn't appear to have received meaningful commits from the harmful actor](https://git.tukaani.org/?p=xz-java.git;a=shortlog). And indeed, [only 1 commit that changes code](https://git.tukaani.org/?p=xz-java.git;a=commit;h=8e46fdf903563b75849a37150be1cbf51ba12c53), and I've reviewed it, it looks fine. So I have no specific concerns with regards to xz-java in vallang.

However, I did lead me to think about, why do we have it in vallang? It's only used in the binary serializer, in a compression mode that was up until very recently not working. I don't think there exists any files that use that compression mode. Especially since there has been no release of vallang with a working `EXTREME` level of compression.

I think we could remove the xz-java dependency, and stop support for that extreme compression mode, without hurting any user. And throw an exception in the reader to use an older version to downgrade the file to a lower level of compresssion (which I think nobody will have ever hit).

**Comment by jurgenvinju** [comment]
Let's do it. Less is more.
