### ISSUE TITLE
failed wysiwyg random test with a complex example

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/vallang#39]
For the record:

```
[ERROR]   IValueTests.testWysiwyg:51 reading back "59"(false,-6)[@FgG1217=($6404-03-11T09:37:06.202+00:00$:<"","">,$2020-10-26T18:36:56.342+00:00$:<"kc","햿ŏŤD">,$0374-02-28T13:59:16.535+00:00$:<"","">,$5254-11-30T22:54:53.946+00:00$:<"","f792">),@JhI4449=[$2020-05-31T23:30:19.184+00:00$,$2020-03-24T01:33:01.663+00:00$],@vRf1459=false,@Okrg81h=1193539202r2144242729] produced something different ==> expected: io.usethesource.vallang.impl.fields.AnnotatedNodeFacade@52d84959<"59"(false,-6)[@FgG1217=($6404-03-11T09:37:06.202+00:00$:<"","">,$2020-10-26T18:36:56.342+00:00$:<"kc","햿ŏŤD">,$0374-02-28T13:59:16.535+00:00$:<"","">,$5254-11-30T22:54:53.946+00:00$:<"","f792">),@JhI4449=[$2020-05-31T23:30:19.184+00:00$,$2020-03-24T01:33:01.663+00:00$],@vRf1459=false,@Okrg81h=1193539202r2144242729]> but was: io.usethesource.vallang.impl.fields.AnnotatedNodeFacade@693b3903<"59"(false,-6)[@FgG1217=($6404-03-11T09:37:06.202+00:00$:<"","">,$2020-10-26T18:36:56.342+00:00$:<"kc","햿ŏŤD">,$0374-02-28T13:59:16.535+00:00$:<"","">,$5254-11-30T22:54:53.946+00:00$:<"","f792">),@JhI4449=[$2020-05-31T23:30:19.184+00:00$,$2020-03-24T01:33:01.663+00:00$],@vRf1459=false,@Okrg81h=1193539202r2144242729]>
```

* This happened on my local machine and is not reproducible without knowing the random seed. The example still needs simplication, but there is enough information to copy the parameter values and call the test again manually.
* io.usethesource.vallang.impl.fields.AnnotatedNodeFacade has toString implemented the right way, so it's something deeper?
* junit5.Assertions.assertEquals only prints the class name and the object if the strings are equal. So in this case the strings are equal but `equals` is not true.

**Comment by DavyLandman** [comment]
you know, in the rascal random tester I've added code that would in case of finding a complex failure, retry the same function, but then tighter random settings, to help simplifiy the problem. if that's possible with junit, that would help in reducing the test case.

For rascal this automatically cuts down on all kinds of cruft in the repo-case.

(yes I agree that in theory could surface other bugs than the one that initially triggered it, but if that's the case, then it would still have found another bug, and the complicated one will show-up later again)

**Comment by DavyLandman** [comment]
I just tried to make a repo for this, but I think the value that was put into the test was different than the printed one, because even rebuilding this value completely from the ground up, the test still succceeds (and printing it does show the same string).

Maybe we have a `toString` that fails? and that the value put as argument was slightly different than the one we just saw?

**Comment by jurgenvinju** [comment]
So from your experiment we can conclude that a value was printed which had a different in-memory representation than the reference value. Hypotheses:

* an equals method which was implemented wrongly (producing false where it should have produced true)
   * this may happen sound like something about annotations went wrong, but that would have been the inverse situation I believe. `equals` should include annotations (and isEqual not).
   * we forgot to override `equals and hashCode` somewhere, like in one of those annotation or keyword parametere wrapper classes
   * we have a rarely triggered bug in an existing equals method, let's say one of the locations or the datetime implementations.

**Comment by jurgenvinju** [comment]
Another data point, `isomorphic` failed with this trace and I suspect its the same bug:

```
[ERROR] testIsomorphicText{IValue, IValue}[1817]  Time elapsed: 0.014 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: "MJ"(5.9289735818642075,"\u1680\u00a0\u3000\n\t\t","OVTk"({$4535-05-31T08:15:59.070+00:00$},|SQ:///|,false),0.0)[@oJEgfsk="v",@XBkHesZ=1201380218r569003461,@PiXocu4=(),@DGR8617=[0,0,0],@aRh3644="TeV"((5:(|b:///|:4.674695947470578,|V:///|:386080964r136365821),564578238:(|d:///|:0,|j:///|:-0.6543539116674302),0:()),0.0)] and "MJ"(5.9289735818642075,"\u1680\u00a0\u3000\n\t\t","OVTk"({$4535-05-31T08:15:59.070+00:00$},|SQ:///|,false),0.0)[@oJEgfsk="v",@XBkHesZ=1201380218r569003461,@PiXocu4=(),@DGR8617=[0,0,0],@aRh3644="TeV"((5:(|b:///|:4.674695947470578,|V:///|:386080964r136365821),564578238:(|d:///|:0,|j:///|:-0.6543539116674302),0:()),0.0)]should be equal because they look the same. ==> expected: io.usethesource.vallang.impl.fields.AnnotatedNodeFacade@3950f973<"MJ"(5.9289735818642075,"\u1680\u00a0\u3000\n\t\t","OVTk"({$4535-05-31T08:15:59.070+00:00$},|SQ:///|,false),0.0)[@oJEgfsk="v",@XBkHesZ=1201380218r569003461,@PiXocu4=(),@DGR8617=[0,0,0],@aRh3644="TeV"((5:(|b:///|:4.674695947470578,|V:///|:386080964r136365821),564578238:(|d:///|:0,|j:///|:-0.6543539116674302),0:()),0.0)]> but was: io.usethesource.vallang.impl.fields.AnnotatedNodeFacade@1d6d374f<"MJ"(5.9289735818642075,"\u1680\u00a0\u3000\n\t\t","OVTk"({$4535-05-31T08:15:59.070+00:00$},|SQ:///|,false),0.0)[@oJEgfsk="v",@XBkHesZ=1201380218r569003461,@PiXocu4=(),@DGR8617=[0,0,0],@aRh3644="TeV"((5:(|b:///|:4.674695947470578,|V:///|:386080964r136365821),564578238:(|d:///|:0,|j:///|:-0.6543539116674302),0:()),0.0)]>
```

**Comment by jurgenvinju** [comment]
Notice how both values are a `AnnotatedNodeFacade` at the top. That might be a coincidence, but for now its the code to scrutinize.

**Comment by jurgenvinju** [comment]
This one was resolved. The issue was caused by the empty tuple type of nodes which have only keyword parameter and no positional parameters. This tuple type was sometimes allocated as TupleTypeWithFieldNames and sometimes as a normal TupleType.
