### ISSUE TITLE
What is the status of `removeKey`?

### ISSUE THREAD

**Issue by PaulKlint** [usethesource/vallang#5]
The `IMap` interface provides a `removeKey` method. However, `io.usethesource.vallang.impl.AbstractMap` throws an `UnsupportedOperationException` for it.

When is an implementation of `removeKey` to be expected? Thanks in advance.

**Comment by msteindorfer** [comment]
Blame shows commit 27429a3e6ae5beb8b0037c6ba873f041926f16e6 to be the origin of introducing this API method. It is unfortunate that it wasn't fully implemented for all cases back at the time.

Thanks to @DavyLandman for providing a fix for this issue.
