### ISSUE TITLE
Arithmetic division by zero not handled correct

### ISSUE THREAD

**Issue by AJGHM-Khonraad** [usethesource/vallang#8]
Entering just "3/0" in the Rascal REPL correctly reports ArithmeticException("/ by zero"). However, entering "0/0" evaluates to 0, which I think is incorrect. As it turned out, this had to do with an 'optimisation' in the evaluation in the class io.usethesource.vallang.impl.primitive.IntegerValue.

I corrected and tested this, and issued a pull request. #7

**Comment by jurgenvinju** [comment]
thanks @AJGHM-Khonraad ! Should have done this fix a long time ago.
